### ISSUE TITLE
MouseEvents should change appearance

### ISSUE THREAD

**Issue by EikeSchwass** [Kittyfisto/Metrolib#15]
Unless I'm missing something the controls don't react to mouse events.

**Comment by Kittyfisto** [comment]
Can you give me an example of which controls you're using?
If you download the sources and build them, does the sample app exhibit the same behaviour?

**Comment by EikeSchwass** [comment]
I can't reproduce the problem anymore. So I guess I had an error somewhere else in my code which somehow prevented the controls from reacting to mouse events. Works like a charm and great lib! You can consider this issue resolved.

**Comment by Kittyfisto** [comment]
I'm glad it's working again and thanks for the praise ;)
